name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # run when you push to main (change if your default branch differs)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          # signal to next.config.js that we are deploying to GitHub Pages
          GITHUB_PAGES: '1'
        run: |
          npm run build
          npm run export

      - name: Create .nojekyll
        run: echo > out/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
